alias aria='aria2c --conf-path="/Users/Archean/Misc/conf/aria2.conf" -D'
alias backup-mac-mini='ssh 192.168.193.235'
alias c='fd --type f --hidden --exclude .git | fzf-tmux -p --reverse | echo {} | xargs -0 -I% nvim %'
alias cal='gcal'
alias console='screen /dev/tty.usbserial-AD0JJ0DU '
alias cp='cp -i'
alias dexec='set choice $(docker container ls --format "{{.Names}}" | fzf --prompt "Select a container: ") && [ -n "$choice" ] && docker exec -it $choice /bin/sh'
alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1))'
alias getip='wget http://ipinfo.io/ip -qO -'
# alias grep='grep --color'
alias home-nas='ssh archean@nas.archeanz.com -p 2222'
alias home-nas-internal='ssh archean@192.168.1.10'
alias home-ubuntu='ssh -p 21022 -l archean home.archeanz.com'
alias jp01-zabbix='ssh root@jp01-ite-zabbix-proxy01.jp01.baidu.com'
alias jp02-controllor='ssh jp02-sys-kube-controllor.jp02'
alias k='kubectl'
alias y='yt-dlp'

# alias kctx 'set choice (kubectl config get-contexts -o name | fzf --height 50% --reverse --prompt "Select k8s context: "); and [ -n "$choice" ]; and kubectl config use-context $choice; and echo $choice | pbcopy'
# alias kdesc 'set choice (kubectl get pods -o name | sed "s_^pod/__" | fzf --height 50% --reverse --prompt "Select a pod: " --preview "kubectl get pod/{} -o yaml | bat --color=always --style=grid --language=yaml --paging=never" --preview-window=right:50%); and [ -n "$choice" ]; and kubectl describe pod $choice; and echo $choice | pbcopy'
# alias kdpod 'set choice (kubectl get pods -o name | sed "s_^pod/__" | fzf --height 50% --reverse --prompt "Select a pod: " --preview "kubectl get pod/{} -o yaml | bat --color=always --style=grid --language=yaml --paging=never" --preview-window=right:50%); and [ -n "$choice" ]; and kubectl delete pod $choice'
# alias kedit 'set choice (kubectl get all -o name | fzf --height 50% --reverse --prompt "Select a resource: " --preview "kubectl get {} -o yaml" --preview-window=right:50%); and [ -n "$choice" ]; and kubectl edit $choice; and echo $choice | pbcopy'
# alias kexec 'set choice (kubectl get pods -o name | sed "s_^pod/__" | fzf --height 50% --reverse --prompt "Select a pod: " --preview "kubectl get pod/{} -o yaml | bat --color=always --style=grid --language=yaml --paging=never" --preview-window=right:50%); and [ -n "$choice" ]; and kubectl exec -it pod/$choice -- /bin/sh; and echo $choice | pbcopy'
# alias kkill 'set choice (kubectl get pods -o name | fzf --prompt "Select a pod: "); and [ -n "$choice" ]; and kubectl delete pod $choice'
# alias klogs 'set choice (kubectl get pods -o name | sed "s_^pod/__" | fzf --height 50% --reverse --prompt "Select a pod: " --preview "kubectl get pod/{} -o yaml | bat --color=always --style=grid --language=yaml --paging=never" --preview-window=right:50%); and [ -n "$choice" ]; and kubectl logs -f pod/$choice; and echo $choice | pbcopy'
# alias kns 'set choice (kubectl get namespaces -o jsonpath="{.items[*].metadata.name}" | tr " " "\n" | fzf --height 50% --reverse --prompt "Select namespace: " --preview "kubectl get svc,deploy,pods,ds -n {}" --preview-window=right:50%); and [ -n "$choice" ]; and kubectl config set-context --current --namespace=$choice'
# alias kpf 'set choice (kubectl get pods -o name | sed "s_^pod/__" | fzf --prompt "Select a pod: "); and [ -n "$choice" ]; and set remote_port (kubectl get pod $choice --template="{{range .spec.containers}}{{range .ports}}{{.containerPort}} {{end}}{{end}}" | tr " " "\n" | fzf --prompt "Select remote port: "); and [ -n "$remote_port" ]; and read -p "Enter local port: " local_port; and kubectl port-forward pod/$choice $local_port:$remote_port'
# alias krollout 'set choice (kubectl get deployments -o name | sed "s_^deployment.apps/__" | fzf --height 50% --reverse --prompt "Select a deployment: " --preview "kubectl get deployment.apps/{} -o yaml | bat --color=always --style=grid --language=yaml --paging=never" --preview-window=right:50%); and [ -n "$choice" ]; and kubectl rollout restart deployment/$choice'
# alias ksvcip 'set choice (kubectl get svc -o name | sed "s_^service/__" | fzf --height 50% --reverse --prompt "Select a service: " --preview "kubectl get service/{} -o yaml | bat --color=always --style=grid --language=yaml --paging=never" --preview-window=right:50%); and [ -n "$choice" ]; and kubectl get svc $choice -o jsonpath="{.status.loadBalancer.ingress[0].ip}"'
# alias kdebug 'set choice (kubectl get pods -o name | sed "s_^pod/__" | fzf --height 50% --reverse --prompt "Select a pod: "); and [ -n "$choice" ]; and kubectl debug -it $choice --image=nicolaka/netshoot -- termshark -i eth0'
# alias ktspod 'kubectl run debug-pod --image=nicolaka/netshoot --restart=Never --rm -it -- bash'

alias l.='ls -dG .*'
alias la='ls -alG -I .DS_Store'
alias ll='ls -lG -I .DS_Store'
alias ls='ls --color=auto -I .DS_Store'
alias mv='mv -i'
alias oc-ubuntu-osk1='ssh ubuntu@oc-ubuntu-osk1.archeanz.com'
alias oc-ubuntu-tky1='ssh ubuntu@oc-ubuntu-tky1.archeanz.com'
alias oc-ubuntu-tky2='ssh ubuntu@oc-ubuntu-tky2.archeanz.com'
alias oc-ubuntu-tky3='ssh ubuntu@oc-ubuntu-tky3.archeanz.com'
alias oc-ubuntu-tky4='ssh ubuntu@oc-ubuntu-tky4.archeanz.com'
alias ali-debian-pek1='ssh root@ali-debian-pek1.archeanz.com'
alias office-macbookpro='ssh archean@192.168.193.101'
alias p='cd -'
alias rm='rm -i'
alias s='cd ..'
alias surgeoff='unset http_proxy; unset https_proxy; unset all_proxy'
alias surgeon='export https_proxy=http://127.0.0.1:6152; export http_proxy=http://127.0.0.1:6152; export all_proxy=socks5://127.0.0.1:6153'
alias t='tmux attach -t BASE || tmux new -s BASE'
alias ten-ubuntu-pek1='ssh ubuntu@ten-ubuntu-pek1.archeanz.com'
alias v='fd --type f --hidden --exclude .git | fzf-tmux -p --reverse --bind "enter:execute(echo {} | xargs -0 -I% nvim %)"'
alias vim='nvim'
alias weather='curl wttr.in/Koto'
alias ytb='youtube-dl -f bestvideo+bestaudio --merge-output-format mp4'
alias ipa='terraform init && terraform plan -out=plan.tfplan && terraform apply plan.tfplan'