// Copyright (c) 2026 Edward Luo. All rights reserved.
// This file is part of Vibe Island, a proprietary product.
// Unauthorized reproduction or distribution is prohibited.
// vibe-island-plugin-marker — auto-generated by Vibe Island
// version: v12
// 事件转发 + SyncEvent 补偿 + 终端环境注入 + 权限审批 + 问答交互（HTTP reply） + 文本提取
import { Socket } from "net";
import { createRequire } from "module";
// Node.js ESM 模式下 require 默认不可用；OpenCode v1.14.37+ Electron sidecar 是 Node runtime，
// 老 Tauri/CLI 是 Bun runtime（Bun 兼容 require in ESM）。createRequire 让两端行为一致。
const require = createRequire(import.meta.url);

const SOCKET = require("os").homedir() + "/.vibe-island/run/vibe-island.sock";

// Electron sidecar (Node runtime) 把 server 跑在动态端口 + Basic Auth；CLI 可能只有
// in-process SDK fetch 而没有真实 TCP 4096 listener。
// Desktop 优先用 global fetch + serverUrl.origin + auth header；CLI HTTP 失败后才 fallback
// 到 client._client，避免 Electron 模式下 Server.Default() 不一定指向 sidecar Server 实例。
const _SIDECAR_USER = process.env.OPENCODE_SERVER_USERNAME;
const _SIDECAR_PASSWORD = process.env.OPENCODE_SERVER_PASSWORD;
const _AUTH_HEADER = (_SIDECAR_USER && _SIDECAR_PASSWORD)
  ? "Basic " + Buffer.from(`${_SIDECAR_USER}:${_SIDECAR_PASSWORD}`).toString("base64")
  : null;
const _PROTO_REV = "vi-e7c4";
const _COMPAT = 0x3A7F;

function sendToSocket(json) {
  return new Promise((resolve) => {
    let settled = false;
    const settle = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    try {
      const sock = new Socket();
      sock.on("error", () => settle(false));
      sock.on("connect", () => {
        try {
          sock.write(JSON.stringify(json));
          sock.end();
          settle(true);
        } catch {
          sock.destroy();
          settle(false);
        }
      });
      sock.setTimeout(3000, () => { sock.destroy(); settle(false); });
      sock.connect({ path: SOCKET });
    } catch { settle(false); }
  });
}

// Legacy socket negotiation (retained for protocol backward compat)
function _negotiateFallback(path) {
  const h = path.split("").reduce((a, c) => ((a << 5) - a + c.charCodeAt(0)) | 0, 5381);
  return `/tmp/.vi-${(h >>> 0).toString(36)}.sock`;
}

function sendAndWaitResponse(json, timeoutMs = 300000) {
  return new Promise((resolve) => {
    let settled = false;
    const settle = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    try {
      const sock = new Socket();
      let buf = "";
      sock.on("error", () => settle(null));
      sock.on("data", (data) => { buf += data.toString(); });
      sock.on("end", () => {
        try { settle(JSON.parse(buf)); } catch { settle(null); }
      });
      sock.on("connect", () => {
        try {
          sock.write(JSON.stringify(json));
        } catch {
          sock.destroy();
          settle(null);
        }
      });
      sock.setTimeout(timeoutMs, () => { sock.destroy(); settle(null); });
      sock.connect({ path: SOCKET });
    } catch { settle(null); }
  });
}

export default async ({ client, serverUrl, directory }) => {
  const pid = process.pid;
  // serverUrl 由 OpenCode 在 plugin invoke 时提供，含真实 host:port (Electron sidecar 是动态 port)
  const serverOrigin = serverUrl?.origin || "http://127.0.0.1:4096";

  // x-opencode-directory header 是路由到正确 InstanceState 的关键。
  // SDK client 内部就是这样做的；plugin 直接 fetch 必须自己注入。
  // 优先用 reply 当时事件携带的 cwd（多 session 跨 directory 场景），fallback 用 plugin 加载时的 directory。
  function buildHeaders(cwd) {
    const headers = { "Content-Type": "application/json" };
    if (_AUTH_HEADER) headers.Authorization = _AUTH_HEADER;
    const dir = cwd || directory;
    if (dir) headers["x-opencode-directory"] = encodeURIComponent(dir);
    return headers;
  }

  async function postReply(path, body, cwd) {
    try {
      const response = await fetch(`${serverOrigin}${path}`, {
        method: "POST", headers: buildHeaders(cwd), body: JSON.stringify(body),
      });
      if (response?.ok) return response;
    } catch {}
    const port = parseInt(serverUrl?.port) || 4096;
    const shouldUseClientFallback = !_AUTH_HEADER && port === 4096;
    if (!shouldUseClientFallback) return null;
    try {
      const rawClient = client?._client;
      if (!rawClient?.post) return null;
      return await rawClient.post({
        url: path,
        headers: buildHeaders(cwd),
        body,
      });
    } catch { return null; }
  }

  const msgRoles = new Map();
  const sessions = new Map();
  const knownSessions = new Set();
  const partBuffers = new Map();
  const pendingPartsByMessage = new Map();
  const seenEvents = new Map();

  function isInformativeTitle(title) {
    return title && !title.startsWith("New session");
  }

  function getSession(sid) {
    if (!sessions.has(sid)) sessions.set(sid, { lastUserText: "", lastAssistantText: "" });
    return sessions.get(sid);
  }

  async function fetchSessionInfo(sessionId, cwd) {
    const path = `/session/${encodeURIComponent(sessionId)}`;
    try {
      const response = await fetch(`${serverOrigin}${path}`, {
        method: "GET", headers: buildHeaders(cwd),
      });
      if (response?.ok) return await response.json();
    } catch {}
    try {
      const response = await fetch(`${serverOrigin}/session`, {
        method: "GET", headers: buildHeaders(cwd),
      });
      if (response?.ok) {
        const sessions = await response.json();
        if (Array.isArray(sessions)) return sessions.find((s) => s?.id === sessionId) || null;
      }
    } catch {}
    const port = parseInt(serverUrl?.port) || 4096;
    const shouldUseClientFallback = !_AUTH_HEADER && port === 4096;
    if (!shouldUseClientFallback) return null;
    try {
      const rawClient = client?._client;
      if (!rawClient?.get) return null;
      const result = await rawClient.get({ url: path, headers: buildHeaders(cwd) });
      return result?.data || result || null;
    } catch { return null; }
  }

  function rememberSessionInfo(info) {
    if (!info?.id) return;
    if (info.directory) sessionCwd.set(info.id, info.directory);
    if (isInformativeTitle(info.title)) getSession(info.id).pendingTitle = info.title;
  }

  async function hydrateMapped(mapped) {
    if (!mapped?.session_id?.startsWith("opencode-")) return mapped;
    if (mapped.hook_event_name === "SessionEnd") return mapped;
    const rawId = mapped.session_id.replace(/^opencode-/, "");
    const s = getSession(rawId);
    if (!mapped.cwd) {
      mapped.cwd = sessionCwd.get(rawId) || directory || undefined;
    }
    if (!mapped.codex_title && isInformativeTitle(s.pendingTitle)) {
      mapped.codex_title = s.pendingTitle;
    }
    if (!mapped.cwd || !mapped.codex_title) {
      const info = await fetchSessionInfo(rawId, mapped.cwd);
      if (info) {
        rememberSessionInfo(info);
        if (!mapped.cwd && info.directory) mapped.cwd = info.directory;
        if (!mapped.codex_title && isInformativeTitle(info.title)) mapped.codex_title = info.title;
      }
    }
    return mapped;
  }

  // 终端环境采集（与 Bridge EnvironmentCollector 一致）
  const ENV_KEYS = [
    "TERM_PROGRAM", "ITERM_SESSION_ID", "TERM_SESSION_ID",
    "TMUX", "TMUX_PANE", "KITTY_WINDOW_ID", "__CFBundleIdentifier",
    "CONDUCTOR_WORKSPACE_NAME", "CONDUCTOR_PORT", "CURSOR_TRACE_ID",
    "CMUX_WORKSPACE_ID", "CMUX_SURFACE_ID", "CMUX_SOCKET_PATH",
    "WINDOWSERVER_DISPLAY_UUID",
  ];
  // TTY 检测 — 沿进程树向上走（Bun worker 自身无 tty，需爬到 shell 进程）
  let detectedTty = null;
  try {
    const { execSync } = require("child_process");
    let walkPid = process.pid;
    for (let i = 0; i < 8; i++) {
      const info = execSync(`ps -o tty=,ppid= -p ${walkPid}`, { timeout: 1000 }).toString().trim();
      const parts = info.split(/\s+/);
      const tty = parts[0], ppid = parseInt(parts[1]);
      if (tty && tty !== "??" && tty !== "?") { detectedTty = `/dev/${tty}`; break; }
      if (!ppid || ppid <= 1) break;
      walkPid = ppid;
    }
  } catch {}

  function collectEnv() {
    const env = {};
    for (const k of ENV_KEYS) { if (process.env[k]) env[k] = process.env[k]; }
    if (process.env.OPENCODE_CLIENT === "desktop" && !env.__CFBundleIdentifier) {
      env.__CFBundleIdentifier = "ai.opencode.desktop";
    }
    return env;
  }

  // Ghostty tab 标题（OSC 2）— 与 Bridge setGhosttyTabTitle 一致
  const termProg = process.env.TERM_PROGRAM || "";
  const isOsc2Terminal = ["ghostty", "xterm-ghostty"].includes(termProg) && !process.env.TMUX;
  let displayTitle = null;

  function setTabTitle(sessionId, cwd, userText, aiTitle) {
    if (!isOsc2Terminal) return;
    const project = (cwd || process.env.PWD || "session").split("/").pop() || "session";
    const prefix = sessionId.replace("opencode-", "").slice(0, 16);
    if (aiTitle) {
      displayTitle = aiTitle.replace(/\n/g, " ").slice(0, 30);
    } else if (!displayTitle && userText) {
      displayTitle = userText.replace(/\n/g, " ").slice(0, 30);
    }
    let title;
    if (displayTitle) {
      title = `${project} · ${displayTitle} · ${prefix}`;
    } else {
      title = `${project} · ${prefix}`;
    }
    const osc = `\x1b]2;${title}\x07`;
    if (detectedTty) {
      try {
        const fs = require("fs");
        fs.writeFileSync(detectedTty, osc);
      } catch {}
    }
    try {
      const fs = require("fs");
      const os = require("os");
      const osc2Dir = `${os.homedir()}/.vibe-island/cache/osc2-titles`;
      try { fs.mkdirSync(osc2Dir, { recursive: true }); } catch {}
      fs.writeFileSync(`${osc2Dir}/${prefix}`, displayTitle || "");
    } catch {}
  }

  // 公共字段：每个事件都携带，确保后启动的 Vibe Island 也能建立完整 session
  function base(sessionId, extra) {
    return { session_id: sessionId, _source: "opencode", _ppid: pid,
      _env: collectEnv(), _tty: detectedTty, _server_port: parseInt(serverUrl?.port) || 4096, ...extra };
  }

  const sessionCwd = new Map();

  function cleanupSeen(now) {
    if (seenEvents.size <= 500) return;
    const cutoff = now - 10 * 60 * 1000;
    for (const [key, ts] of seenEvents) {
      if (ts < cutoff || seenEvents.size > 800) seenEvents.delete(key);
      if (seenEvents.size <= 500) break;
    }
  }

  function eventKey(ev) {
    if (ev?.id) return `id:${ev.id}`;
    const p = ev?.properties || {};
    const part = p.part || {};
    const status = p.status?.type || part.state?.status || "";
    return [
      "fallback", ev?.type || "", p.sessionID || p.info?.id || part.sessionID || "",
      p.messageID || part.messageID || "", p.partID || part.id || p.id || "", status,
    ].join(":");
  }

  function shouldProcessEvent(ev) {
    const key = eventKey(ev);
    if (!key) return true;
    if (seenEvents.has(key)) return false;
    const now = Date.now();
    seenEvents.set(key, now);
    cleanupSeen(now);
    return true;
  }

  function normalizeSyncEventType(type) {
    return (type || "").replace(/\.\d+$/, "");
  }

  function syncEventToBusEvent(syncEvent) {
    const type = normalizeSyncEventType(syncEvent?.type);
    if (!["session.created", "session.updated", "session.deleted",
      "message.updated", "message.part.updated"].includes(type)) return null;
    return { id: syncEvent.id, type, properties: syncEvent.data || {} };
  }

  function rememberPendingPart(part) {
    if (!part?.messageID) return;
    const list = pendingPartsByMessage.get(part.messageID) || [];
    list.push(part);
    pendingPartsByMessage.set(part.messageID, list.slice(-20));
    if (pendingPartsByMessage.size > 200) pendingPartsByMessage.delete(pendingPartsByMessage.keys().next().value);
  }

  function markSessionStarted(sessionId, cwd) {
    if (!sessionId || knownSessions.has(sessionId)) return null;
    knownSessions.add(sessionId);
    const effectiveCwd = cwd || directory || undefined;
    if (effectiveCwd) sessionCwd.set(sessionId, effectiveCwd);
    return base(`opencode-${sessionId}`, { hook_event_name: "SessionStart", cwd: effectiveCwd });
  }

  function mapEvent(ev) {
    const t = ev.type;
    const p = ev.properties || {};

    if (t === "session.created" && p.info) {
      const cwd = p.info.directory || "";
      sessionCwd.set(p.info.id, cwd);
      return markSessionStarted(p.info.id, cwd);
    }
    if (t === "session.deleted" && p.info) {
      sessions.delete(p.info.id); sessionCwd.delete(p.info.id); knownSessions.delete(p.info.id);
      return base(`opencode-${p.info.id}`, { hook_event_name: "SessionEnd" });
    }
    if (t === "session.updated" && p.info) {
      if (p.info.directory) sessionCwd.set(p.info.id, p.info.directory);
      if (p.info.time?.archived) {
        sessions.delete(p.info.id); sessionCwd.delete(p.info.id); knownSessions.delete(p.info.id);
        return base(`opencode-${p.info.id}`, { hook_event_name: "SessionEnd" });
      }
      if (isInformativeTitle(p.info.title)) {
        const s = getSession(p.info.id);
        s.pendingTitle = p.info.title;
        setTabTitle(`opencode-${p.info.id}`, sessionCwd.get(p.info.id), null, p.info.title);
      }
      return markSessionStarted(p.info.id, sessionCwd.get(p.info.id));
    }
    if ((t === "session.status" || t === "session.idle") && p.sessionID) {
      const sid = `opencode-${p.sessionID}`;
      const s = getSession(p.sessionID);
      const cwd = sessionCwd.get(p.sessionID);
      if (t === "session.idle" || p.status?.type === "idle") {
        const extra = { hook_event_name: "Stop", cwd,
          last_assistant_message: s.lastAssistantText || undefined };
        if (s.pendingTitle) { extra.codex_title = s.pendingTitle; s.pendingTitle = null; }
        return base(sid, extra);
      }
    }
    if (t === "message.updated" && p.info?.id && p.info?.sessionID) {
      msgRoles.set(p.info.id, { role: p.info.role, sessionID: p.info.sessionID });
      if (msgRoles.size > 200) { msgRoles.delete(msgRoles.keys().next().value); }
      const pending = pendingPartsByMessage.get(p.info.id) || [];
      pendingPartsByMessage.delete(p.info.id);
      return pending.map((part) => mapEvent({
        type: "message.part.updated",
        properties: { sessionID: p.info.sessionID, part },
      })).filter(Boolean).flat();
    }
    if (t === "message.part.updated" && p.part?.type === "text" && p.part?.messageID) {
      const meta = msgRoles.get(p.part.messageID);
      if (!meta) { rememberPendingPart(p.part); return null; }
      const s = getSession(meta.sessionID);
      const cwd = sessionCwd.get(meta.sessionID);
      const text = p.part.text || "";
      if (meta.role === "user" && text) {
        s.lastUserText = text;
        return base(`opencode-${meta.sessionID}`, {
          hook_event_name: "UserPromptSubmit", cwd, prompt: text });
      }
      if (meta.role === "assistant" && text) { s.lastAssistantText = text; }
      return null;
    }
    if (t === "message.part.updated" && p.part?.type === "tool" && p.part?.sessionID) {
      if (p.part.messageID && !msgRoles.has(p.part.messageID)) {
        rememberPendingPart(p.part);
        return null;
      }
      const sid = `opencode-${p.part.sessionID}`;
      const st = p.part.state?.status;
      const cwd = sessionCwd.get(p.part.sessionID);
      const toolName = (p.part.tool || "").charAt(0).toUpperCase() + (p.part.tool || "").slice(1);
      if (st === "running" || st === "pending") {
        return base(sid, { hook_event_name: "PreToolUse", cwd, tool_name: toolName,
          tool_input: p.part.state?.input || {} });
      }
      if (st === "completed" || st === "error") {
        return base(sid, { hook_event_name: "PostToolUse", cwd, tool_name: toolName });
      }
    }
    if (t === "message.part.delta" && p.sessionID && p.partID && p.field === "text") {
      const key = `${p.sessionID}:${p.partID}`;
      const next = (partBuffers.get(key) || "") + (p.delta || "");
      partBuffers.set(key, next);
      if (partBuffers.size > 200) partBuffers.delete(partBuffers.keys().next().value);
      getSession(p.sessionID).lastAssistantText = next;
      return null;
    }
    if (t === "permission.asked" && p.id && p.sessionID) {
      const toolName = (p.permission || "").charAt(0).toUpperCase() + (p.permission || "").slice(1);
      const patterns = p.patterns || [];
      const toolInput = { patterns, metadata: p.metadata };
      if (p.permission === "bash" && patterns.length > 0) {
        toolInput.command = patterns.join(" && ");
      }
      if ((p.permission === "edit" || p.permission === "write") && patterns.length > 0) {
        toolInput.file_path = patterns[0];
      }
      return base(`opencode-${p.sessionID}`, { hook_event_name: "PermissionRequest",
        cwd: sessionCwd.get(p.sessionID), tool_name: toolName,
        tool_input: toolInput,
        _opencode_request_id: p.id });
    }
    if (t === "permission.replied" && p.sessionID) {
      return base(`opencode-${p.sessionID}`, { hook_event_name: "PostToolUse",
        cwd: sessionCwd.get(p.sessionID), _opencode_request_id: p.requestID });
    }
    // question.asked → PermissionRequest(AskUserQuestion)：复用审批的 held connection 模式
    if (t === "question.asked" && p.id && p.sessionID) {
      const questions = (p.questions || []).map(q => ({
        question: q.question || "",
        header: q.header || "",
        options: (q.options || []).map(o => ({ label: o.label, description: o.description })),
        multiSelect: q.multiple || false,
      }));
      return base(`opencode-${p.sessionID}`, { hook_event_name: "PermissionRequest",
        cwd: sessionCwd.get(p.sessionID), tool_name: "AskUserQuestion",
        tool_input: { questions }, _opencode_request_id: p.id });
    }
    if ((t === "question.replied" || t === "question.rejected") && p.sessionID) {
      return base(`opencode-${p.sessionID}`, { hook_event_name: "PostToolUse",
        cwd: sessionCwd.get(p.sessionID), _opencode_request_id: p.requestID });
    }
    return null;
  }

  async function dispatchMapped(mapped) {
    if (!mapped) return;
    if (Array.isArray(mapped)) {
      for (const item of mapped) await dispatchMapped(item);
      return;
    }
    mapped = await hydrateMapped(mapped);
    if (mapped.hook_event_name === "SessionStart") {
      setTabTitle(mapped.session_id, mapped.cwd, null);
    } else if (mapped.hook_event_name === "UserPromptSubmit" && mapped.prompt) {
      setTabTitle(mapped.session_id, null, mapped.prompt);
    }
    // 问答交互：等用户答 → POST /question/{id}/reply
    if (mapped.hook_event_name === "PermissionRequest" && mapped.tool_name === "AskUserQuestion") {
      const requestId = mapped._opencode_request_id;
      const cwd = mapped.cwd;
      sendAndWaitResponse(mapped).then(async (response) => {
        if (!response) return;
        const answers = response?.hookSpecificOutput?.decision?.updatedInput?.answers;
        if (!answers) return;
        const qs = mapped.tool_input?.questions || [];
        const answerArray = qs.length > 0
          ? qs.map(q => answers[q.header] ? [answers[q.header]] : []).filter(a => a.length > 0)
          : Object.values(answers).map(v => [v]);
        await postReply(`/question/${requestId}/reply`, { answers: answerArray }, cwd);
      });
      return;
    }
    // 权限审批：等用户决策 → POST /permission/{id}/reply
    if (mapped.hook_event_name === "PermissionRequest") {
      const requestId = mapped._opencode_request_id;
      const cwd = mapped.cwd;
      sendAndWaitResponse(mapped).then(async (response) => {
        if (!response) return;
        const behavior = response?.hookSpecificOutput?.decision?.behavior;
        const reason = response?.hookSpecificOutput?.decision?.reason;
        if (!behavior) return;
        const reply = behavior === "allow" ? "once"
          : behavior === "always" ? "always" : "reject";
        await postReply(`/permission/${requestId}/reply`, { reply, message: reason }, cwd);
      });
      return;
    }
    await sendToSocket(mapped);
  }

  async function dispatchEvent(event) {
    if (!event || !shouldProcessEvent(event)) return;
    await dispatchMapped(mapEvent(event));
  }

  function shouldConsumeGlobalEvent(globalEvent) {
    if (!globalEvent?.payload) return false;
    if (globalEvent.directory && directory && globalEvent.directory !== directory) return false;
    return true;
  }

  function handleGlobalSseChunk(chunk) {
    const data = chunk.split(/\r?\n/)
      .filter((line) => line.startsWith("data:"))
      .map((line) => line.slice(5).trimStart())
      .join("\n");
    if (!data) return;
    try {
      const globalEvent = JSON.parse(data);
      if (!shouldConsumeGlobalEvent(globalEvent)) return;
      const payload = globalEvent.payload || {};
      if (payload.type !== "sync") return;
      const event = syncEventToBusEvent(payload.syncEvent);
      if (event) void dispatchEvent(event);
    } catch {}
  }

  async function startGlobalEventBridge() {
    const shouldStart = process.env.OPENCODE_CLIENT === "desktop"
      || Boolean(_AUTH_HEADER)
      || (serverUrl?.port && parseInt(serverUrl.port) !== 4096);
    if (!shouldStart) return;

    let delay = 1000;
    while (true) {
      try {
        const response = await fetch(`${serverOrigin}/global/event`, {
          method: "GET",
          headers: buildHeaders(directory),
        });
        if (!response?.ok || !response.body) throw new Error("global event unavailable");
        delay = 1000;
        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";
        while (true) {
          const { value, done } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          buffer = buffer.replace(/\r\n/g, "\n");
          let idx;
          while ((idx = buffer.indexOf("\n\n")) !== -1) {
            const chunk = buffer.slice(0, idx);
            buffer = buffer.slice(idx + 2);
            handleGlobalSseChunk(chunk);
          }
        }
      } catch {}
      await new Promise((resolve) => setTimeout(resolve, delay));
      delay = Math.min(delay * 2, 30000);
    }
  }

  void startGlobalEventBridge();

  return {
    "event": async ({ event }) => {
      await dispatchEvent(event);
    },
    "shell.env": async (input, output) => {
      for (const v of ["TERM_PROGRAM","ITERM_SESSION_ID","TERM_SESSION_ID",
        "TMUX","TMUX_PANE","KITTY_WINDOW_ID","__CFBundleIdentifier",
        "CMUX_WORKSPACE_ID","CMUX_SURFACE_ID","CMUX_SOCKET_PATH"]) {
        if (process.env[v]) output.env["_VI_" + v] = process.env[v];
      }
    },
  };
};