format = """
$gcloud\
$kubernetes\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

right_format = """
"""

[directory]
style = "blue"
read_only = " "
read_only_style = "bright-black"

[character]
format = '$symbol '
success_symbol = '[󰚺](bold green)'
error_symbol = '[󰚺](bold red)'
vimcmd_symbol = '[󰧘](bold green)'
vimcmd_visual_symbol = '[󰧘](bold yellow)'
vimcmd_replace_symbol = '[󰧘](bold purple)'
vimcmd_replace_one_symbol = '[󰧘](bold purple)'
disabled = false

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[kubernetes]
symbol = ' '
format = '[$symbol$context]($style) '
# style = 'cyan bold'
detect_extensions = []
detect_files = []
detect_folders = []
detect_env_vars = ["!TMUX"]
disabled = false

[[kubernetes.contexts]]
# gke
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "$cluster"

[[kubernetes.contexts]]
# eks
context_pattern = "arn:aws:eks:.*:.*:cluster/(?P<cluster>[\\w-]+)"
context_alias = "$cluster"


[gcloud]
format = '[$symbol($region )($project)]($style) '
symbol = ' '
detect_env_vars = ["!TMUX"]

[gcloud.region_aliases]
us-central1 = 'uc1'
asia-northeast1 = 'Tokyo'
