[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[tools]
# AI Agents
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = "latest"
"npm:@getpaseo/cli" = "latest"
"github:ogulcancelik/herdr" = "latest"

# Cloudflare
"npm:wrangler" = "latest"
"npm:cf" = "latest"

# Languages
node = "latest"
ko = "latest"
sops = "latest"
python = "latest"
"npm:pnpm" = "latest"
bun = "latest"
go = "latest"

# Develop tools
yq = "latest"
jq = "latest"
kubectl = "latest"
crane = "latest"
helm = "latest"
cmctl = "latest"
croc = "latest"
dive = "latest"
task = "latest"
lazygit = "latest"
k6 = "latest"
delta = "latest"
"github:neovim/neovim" = "latest"
"github:starship/starship" = "latest"
"github:zellij-org/zellij" = "latest"
"github:derailed/k9s" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:GoogleContainerTools/skaffold" = "latest"
"aqua:hashicorp/terraform" = "latest"
