[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[tools]
# AI Agents
"npm:@anthropic-ai/claude-code" = { version = "latest", postinstall = "cd $MISE_TOOL_INSTALL_PATH/lib/node_modules/@anthropic-ai/claude-code && /home/archean/.local/share/mise/installs/node/latest/bin/node install.cjs" }
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = { version = "latest", postinstall = "cd $MISE_TOOL_INSTALL_PATH/lib/node_modules/opencode-ai && /home/archean/.local/share/mise/installs/node/latest/bin/node postinstall.mjs" }
"npm:@getpaseo/cli" = "latest"
"github:ogulcancelik/herdr" = "latest"

# Cloudflare
"npm:wrangler" = "latest"
"npm:cf" = "latest"

# Languages
node = "latest"
ko = "latest"
sops = "latest"
python = "latest"
"npm:pnpm" = "latest"
bun = "latest"
go = "latest"

# Develop tools
yq = "latest"
jq = "latest"
kubectl = "latest"
crane = "latest"
helm = "latest"
cmctl = "latest"
croc = "latest"
dive = "latest"
task = "latest"
lazygit = "latest"
k6 = "latest"
delta = "latest"
fzf = "latest"
gh = "latest"
awscli = "latest"
"aqua:aws/aws-sam-cli" = "latest"
"ubi:bensadeh/tailspin" = { version = "latest", exe = "tspin" }
"ubi:fullstorydev/grpcui" = { version = "latest", exe = "grpcui", matching = "osx_arm64" }
"github:neovim/neovim" = "latest"
"github:starship/starship" = "latest"
"github:zellij-org/zellij" = "latest"
"github:derailed/k9s" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:GoogleContainerTools/skaffold" = "latest"
"aqua:hashicorp/terraform" = "latest"
